apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://<your_git_repo_url>'
    targetRevision: HEAD
    path: monitoring/prometheus-operator
    helm:
      valueFiles:
        - values.yaml
  destination:
    # name of the GKE cluster should be added here
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

