name: 'Terraform CI/CD'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    strategy:
      matrix:
        directory:
          - terraform/buckets
          # - terraform/public-cluster
          # - terraform/private-cluster

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup GCP Credentials
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.0'  # Use the version that suits your needs

      - name: Terraform Init and Plan
        run: |
          terraform init
          terraform validate
          terraform plan
        working-directory: ${{ matrix.directory }}

  terraform-apply:
    name: 'Terraform Apply'
    needs: terraform-plan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    strategy:
      matrix:
        directory:
          - terraform/buckets
          # - terraform/public-cluster
          # - terraform/private-cluster

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup GCP Credentials
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.0'  # Use the version that suits your needs

      - name: Terraform Init and Apply
        run: |
          terraform init
          terraform apply -auto-approve
        working-directory: ${{ matrix.directory }}

